### ISSUE TITLE
软件问题和翻译问题

### ISSUE THREAD

**Issue by AndyandRed** [Rehcramon/MasterDuelCardTranslator#16]
您好，这边遇到了两个问题。第一个问题，启动程序后的出现两个框显示正在启动 Mater Duel Card Translater...的框一直在自主变化大小（电脑系统是win10）。一直变化大小，有点疑惑。第二个问题，就是电子龙核这张牌的效果翻译是按照电子龙的效果来翻译（不知道算不算bug）

https://user-images.githubusercontent.com/98424472/151051364-cad6f979-80ac-4abf-bbd2-381f9dfade6f.mp4

**Comment by Rehcramon** [comment]
第一个问题，视频看起来过于鬼畜了。感觉有点像是命令行本身的问题，如果不影响使用的话建议忽略。我在后面的版本中应该会尝试不展示这个命令行窗口。

第二个问题已知晓，是BUG。原因在于识别卡名的时候，游戏内卡名是当前的名字，而不是原始卡名。这个问题我正在想办法解决。

感谢反馈。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/issues/9

第一个问题已解决，不再展示命令行窗口。
第二个问题我已在这个issue里面记录，本issue就先close了。

**Comment by AndyandRed** [comment]
非常感谢您的工作
