### ISSUE TITLE
一个比较离谱的情况

### ISSUE THREAD

**Issue by CircleRuler** [Rehcramon/MasterDuelCardTranslator#2]
用MDCT_PositionSetup设置好位置后，每次开MasterDuelCardTranslator所打开的命令行窗口都会恰好挡住我设定好的位置，导致没法用。。。

**Comment by CircleRuler** [comment]
试了十几次终于成功了一次，😢

**Comment by Rehcramon** [comment]
这个确实是一个问题，我其实想加一个每次移动MDCT之后记录当前位置的功能。
我现在每次启动都要手动拖MDCT到卡片效果的位置，感觉要逼死强迫症了。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/commit/659b2ab8f37d34fea37225120c6dcdf25a5c8415

目前先把界面移开了，但是命令行还是处理不了。

回头记录下当前位置试试。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/commit/8306b8e12a93ae6de73864d555ebba19397111db

能够记录当前位置了。
