### ISSUE TITLE
电子龙核识别成电子龙

### ISSUE THREAD

**Issue by zhouglang** [Rehcramon/MasterDuelCardTranslator#30]
电子龙核上场之后由于卡名变成了电子龙，翻译软件直接识别成了电子龙。但具有同样性质的电子龙芯、电子龙·次代星则能够正确识别该卡。
目前该问题仅发现电子龙核存在，而电子龙芯、电子龙·次代星、电子龙·凯旋、青眼亚白龙等卡则能正确识别。

**Comment by Rehcramon** [comment]
应该是电子龙核的文本识别失败了转卡名识别出现的问题。我排查一下。
感谢反馈。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/commit/1bcc76555ccc98579a6a5c2b3ab3f706201de84a

已修复，原因是文本数据是旧的实卡文本，而不是MD中的文本。再次感谢反馈。
