### ISSUE TITLE
花札卫-桐-  识别为  花札卫-柳-

### ISSUE THREAD

**Issue by oooldtoy** [Rehcramon/MasterDuelCardTranslator#31]

**Comment by Rehcramon** [comment]
收到，我先确认一下。
感谢反馈。

**Comment by Rehcramon** [comment]
我这边能复现类似的问题，在尝试修复。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/commit/097a33783b88902400e4af6f8dc3690c00bc3024

已修复。再次感谢反馈。
原因是哈希图片时压缩得太厉害，导致10和11的区别以及11和12的区别无法辨认出来。
