### ISSUE TITLE
翻译窗口是空白的，没办法对游戏界面截图

### ISSUE THREAD

**Issue by LiiittlePony** [Rehcramon/MasterDuelCardTranslator#32]
![截图20220227100022520](https://user-images.githubusercontent.com/100499140/155865325-6b56abfb-6b20-4a2f-8c9f-8b0866a838c5.jpg)

**Comment by Rehcramon** [comment]
这个问题比较意外，请看下是否暂停了OCR。

如果不是的话，我得仔细看下哪里出了问题。感谢反馈。

**Comment by LiiittlePony** [comment]
V1.3是要手动选取截图区域的，就是点卡牌描述的左上角，右下角等，可以正常翻译。
但是，V2.0之后的版本都没有这个功能，
我觉得是这个差别导致的，v2.0之后的版本不能正常翻译。










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rehcramon/MasterDuelCardTranslator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 晚上7:35
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [Rehcramon/MasterDuelCardTranslator] 翻译窗口是空白的，没办法对游戏界面截图 (Issue #32)





 
这个问题比较意外，请看下是否暂停了OCR。
 
如果不是的话，我得仔细看下哪里出了问题。感谢反馈。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Rehcramon** [comment]
v2.3把手动选择截图区域的功能重新引入了，还请试用一下，谢谢。

全白我觉得可能是不兼容Windows 7的原因，但是我手上没有可以测试的机子，所以暂时无法验证。
