### ISSUE TITLE
能否增加字体大小修改

### ISSUE THREAD

**Issue by AugusLcz** [Rehcramon/MasterDuelCardTranslator#5]
固定字体大小在大屏幕上比较吃力，能否开放自定义字体大小？

**Comment by Rehcramon** [comment]
可以的。在日程上了。
这个功能预计会以通过改settings.json文件的方法提前上线，暂时不会给用户在界面上直接修改字体大小的功能，还请理解。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/commit/55f8fc68f36ec43c26da3b17fb27761178a2f3b6

可自行在settings.json中font处修改。
