### ISSUE TITLE
窗口捕获

### ISSUE THREAD

**Issue by laxfight** [Rehcramon/MasterDuelCardTranslator#6]
感觉窗口位置可以使用win32获取窗口的position,卡片位置就可以按照比例获取了。
还有个比较骚的方法是用yolo框架进行目标检测

**Comment by Rehcramon** [comment]
了解了，多谢。
win32的API我之后看看会不会效果更好。用pyautogui的原因是这是我搜到的比较容易看懂的框架。
yolo有点超出我的知识范围了，之后如果有空会去学习的。

**Comment by Rehcramon** [comment]
https://github.com/Rehcramon/MasterDuelCardTranslator/commit/debf9509ba1c9bd5b2a7a5a2e88d2acef42287dd

感谢建议。迟迟没有应用的原因是不清楚win32对游戏本身的影响。

现在我认为，使用这个commit的方法会对游戏本身产生微乎其微的影响。其原理是向游戏发送WM_Paint让其更新界面，之后Windows复制这个界面的内容。从我的理解上来看，是可以接受的。
